set echo on

DROP TABLE POSTE CASCADE CONSTRAINTS;
REM Table POSTE supprimée.

DROP TABLE VENTEAGENT CASCADE CONSTRAINTS;
REM Table VENTEAGENT supprimée.

DROP TABLE PERSONNEL CASCADE CONSTRAINTS;
REM Table PERSONNEL supprimée.

DROP TABLE CONTRAT CASCADE CONSTRAINTS;
REM Table CONTRAT supprimée.

DROP TABLE CRENEAU CASCADE CONSTRAINTS;
REM Table CRENEAU supprimée.

DROP TABLE CLIENT CASCADE CONSTRAINTS;
REM Table CLIENT supprimée.

DROP TABLE RECHERCHE CASCADE CONSTRAINTS;
REM Table RECHERCHE supprimée.

DROP TABLE IMMOBILIER CASCADE CONSTRAINTS;
REM Table IMMOBILIER supprimée.

DROP TABLE VILLE CASCADE CONSTRAINTS;
REM Table VILLE supprimée.

DROP TABLE REGION;
REM Table REGION supprimée.

DROP TABLE VENDU;
REM Table VENDU supprimée.

DROP TABLE LOUE;
REM Table LOUE supprimée.

DROP TABLE MAISON;
REM Table MAISON supprimée.

DROP TABLE APPARTEMENT;
REM Table APPARTEMENT supprimée.

DROP TABLE VENTE;
REM Table VENTE supprimée.

DROP TABLE LOCATION;
REM Table LOCATION supprimée.

DROP TABLE PIECE;
REM Table PIECE supprimée.

DROP TABLE PROPRIETAIRE;
REM Table PROPRIETAIRE supprimée.

REM Toutes les tables ont été supprimées.
